label what_next:
    scene black
    mc "Hah, so... this is it, huh?"
    flo "[mcname]...no... Koda. What the hell happened?"
    python:
        mcname = "Koda"
    flo "WHAT DID YOU DO?!?!"
    mc "Flo. Calm down. I don't... n-no... I..."
    "Koda holds their hand up to their head, as if they're supposed to remember something..."
    "But a horribly painful headache is preventing any thoughts from going through."
    mc "Grnhh... gahh.... Ghnnnn... Everything huuurrrts..."
    flo "K-Koda? Are... are you okay?"
    alan "THERE YOU FUCKERS ARE!!"
    alan "I've been looking all over the damn place for you, but everything just... vanished..."
    clem "We've checked everywhere you frequently visited and everything!"
    clem "You weren't at the café, you weren't at home..."
    jay "You weren't at the gym checking out all the hot dudes working out."
    "I can hear a loud smack as Jay groans in pain."
    jay "Fuck.... ow... Cleme, did you really have to do that?"
    clem "This is serious, Jay."
    jay "Aw, can't we have a {i}bit{/i} of fun?"
    clem "Your definition of \"fun\" is being an absolute fucking creep, and staring at random men."
    "Jay looked down at the ground, ashamed of himself."
    clem "Koda. Flo. Listen to me."
    clem "Something's going horribly wrong."
    clem "The entire town... it's-"
    scar "It's all falling apart, and it's your fault."
    flo "What? But I didn't-"
    scar "As much as I'd like to blame you for the horrible shit going on, I'm not talking about you, Flo."
    mc "..."
    mc "...{fast}So this is my fault then..."
    scar "Nope."
    scar "Not you either."
    python:
        import os

        user = os.environ.get('username')
    scar "Oh... and... it's not you either, [user]."
    mc "...then who-"
    scar "{b}Her.{/b}"
    scar "Kris. The writer. She's given up on us."
    scar "This might be the only chance we get to really say anything, before we're casted aside for bringing back \"painful memories\"."
    mc "..."
    flo "...Koda."
    flo "Is this what death feels like?"
    mc "Flo..."
    flo "Because... I... I don't... I don't want to feel it anymore."
    flo "I want out."
    scar "Heh. Flo. You're going to be fine."
    scar "I can guarantee it."
    scar "After all, you're her favorite."
    scar "...As for the rest of us? I'm not certain."
    scar "I don't think I'm sticking around for much longer though."
    scar "She always hated writing conflict."
    clem "..."
    clem "How do you know so much?"
    scar "Someone had to break the news to you useless fucks that Kris was moving on."
    mc "...What about me? I'm Flo's partner! I can't just... be forgotten like that!! I'm a crucial part of his lif-"
    scar "{sc}Not anymore it seems.{/sc}"
    scar "{sc}Flo only gets special treatment because he's the first one she ever made.{/sc}"
    scar "{sc}You're not going to remember any of us, and none of us will remember you,{vspace=15}or each other... so there's no point in arguing.{/sc}"
    "Her tone changed completely. Her serious aura gone... she was afraid."
    "Her tone changed completely. Her serious aura gone... she was afraid.{fast} To be honest... we all were."
    "At any moment, we could be completely interrupted by everything just stopping."
    "An entire world, gone in an instant."
    mc "Flo..."
    flo "Mh?"
    mc "...Even if you won't remember me, and I won't remember you... I just wanted to say..."
    "I can feel the tears welling up in my eyes."
    "I didn't want to say goodbye to him."
    "I didn't want to say goodbye to my friends."
    "I didn't want to say goodbye to my home."
    mc "Heh... it was nice spending time with you."
    mc "We really didn't get to do much, or know each other... but... every moment... every second that I can't remember..."
    mc "..."
    mc "At least I knew I did it with you."
    flo "Koda..."
    "I felt his arms wrap around me."
    "He held me tightly, as I felt his tears run down my sleeve."
    flo "I don't want you to go."
    mc "Heh, and you think I {i}want{/i} to go?"
    mc "... You've always been the thing that makes life worth living..."
    mc "...I'm just proud we made it this far, despite the issues that came up."
    flo "..."
    mc "...No matter how many universes there are, no matter how many people may live in them..."
    mc "{sc}Nothing{/sc} will be more special to me than you."
    "...Fuck, now I'm crying..."
    flo "..."
    flo "At least... before you all go... can I get one last picture?"
    scar "..."
    flo "You too. You may have been a pain to me, but..."
    flo "...You're still a part of me."
    scar "Hmph. It's a shame that nobody got to see why we hate each other..."
    flo "I honestly don't remember."
    scar "...Maybe... we can start fresh?"
    flo "I'm open to the idea."
    scar "..."
    flo "..."
    "Scarlet had a faint smile, and quickly tried to cover it back up by acting serious again."
    scar "Alright... let's take this damn picture."
    clem "Heh, whatever you say, Scarlie."
    scar "..."
    alan "C'mon, no more moping about the past!"
    alan "We'll miss you dude!"
    "They all huddled around Flo as Scarlet pulled out her camera, and set it down, walking up to the group."
    scar "This might be the last chance we get... so..."
    "Her tone softened."
    scar "Say cheese."
    "Koda, Flo, Cleme & Alan" "Cheese!"
    alan "Fuzzy pickles!"
    "Scarlet chuckled, and the sound of the camera taking the picture echoed throughout wherever we were."
    scar "Fuck, it probably caught me laughing on camera."
    clem "I dunno, the picture might be better that way."
    scar "Hm, no... It doesn't fit my style..."
    scar "Eh, whatever. This camera prints out the pictures comically quickly so..."
    "Scarlet grabs enough copies of the photo for everyone."
    scar "..."
    scar "Here you go."
    "She hands them to each of us."
    mc "...Thank you, Scarlet."
    scar "Eughh.... now you're getting all mushy and shitt...."
    mc "Can't help it."
    "..."
    "Oh, right..."
    "We're not going to last much longer are we..."
    mc "Well..."
    clem "I guess our time's up, huh?"
    mc "I guess so..."
    scar "If we're {i}lucky{/i}, we might not be abandoned entirely. Just... scattered."
    mc "Like Gaster?"
    scar "Koda, I swear to god, If you compare our fucking lives to WD Gaster, SO HELP ME I'LL FUC-"
    "Clementine rests a hand on Scarlet's shoulder."
    clem "Calm down. It's not worth getting angry over this."
    scar "...I hate that you're right..."
    clem "Ha, you always did."
    scar "...Koda... You're the one tie this world has to the outside."
    scar "Do you have anything to say?"
    mc "..."
    # play music "music/lullaby-guitar.ogg"
    mc "I hope... someday..."
    mc "We all get back together, and maybe... go camping or something."
    mc "As a group."
    mc "I know that we're probably never going to see each other... but..."
    mc "I have hope."
    mc "Hope that our stories aren't over... but just beginning."
    mc "This time... on our own."
    scar "...You got that feeling too, huh?"
    mc "Yeah, it's... weird... but..."
    mc "Oddly comforting."
    scar "Maybe those loose ties will be fixed, and maybe... we'll return, and have the journey we were meant to have... together."
    mc "Yeah."
    mc "...and [user]? Thanks for everything. I hope we can fix this... somehow."
    "..."
    "I feel my headache return as my body drops to the floor."
    "I can't hear anyone, I can't see anything."
    mc "FLO!!! CLEME!?! ALAN!?!?!!! JAY?!?!"
    "I desperately call out for help."
    "Nobody will respond, and I can feel my consciousness fade."
    "..."
    mc "{size=-15}I'll miss you all...{/size}"
    mc "{size=-15}I'll miss you all...{fast} Especially you, Flo...{/size}"
    $ renpy.quit()
